// Declarations for the tables generated by tools/gen_bindings.py.
#ifndef BUILTIN_BINDINGS_GEN_H
#define BUILTIN_BINDINGS_GEN_H

#include <cstdint>

namespace gdas::gen {

struct ArgSpec {
	const char *name;
	const char *type;
	const char *default_value; // Godot-syntax default expression or nullptr
};

struct MethodSpec {
	const char *cls;
	const char *as_name; // identifier-safe name used in AngelScript
	const char *godot_name; // real method name used for dispatch
	const char *return_type; // nullptr for void
	bool is_vararg;
	bool is_static;
	int argc;
	const ArgSpec *args;
};

struct OperatorSpec {
	const char *cls;
	const char *op; // Godot operator token, e.g. "+", "==", "unary-"
	const char *right_type; // nullptr for unary
	const char *return_type;
	bool reversed; // true when cls is the RIGHT operand (e.g. float * Vector2)
};

struct CtorSpec {
	const char *cls;
	int index; // Godot constructor index (used with variant_construct)
	int argc;
	const ArgSpec *args;
};

struct MemberSpec {
	const char *cls;
	const char *name;
	const char *type;
};

struct EnumValSpec {
	const char *name;
	int64_t value;
};

struct EnumSpec {
	const char *name;
	bool is_bitfield;
	int first_value; // index into global_enum_values
	int count;
};

struct UtilitySpec {
	const char *name;
	const char *return_type;
	bool is_vararg;
	uint32_t hash;
	int argc;
	const ArgSpec *args;
};

extern const MethodSpec builtin_methods[];
extern const int builtin_methods_count;
extern const OperatorSpec builtin_operators[];
extern const int builtin_operators_count;
extern const CtorSpec builtin_ctors[];
extern const int builtin_ctors_count;
extern const MemberSpec builtin_members[];
extern const int builtin_members_count;
extern const EnumValSpec global_enum_values[];
extern const int global_enum_values_count;
extern const EnumSpec global_enums[];
extern const int global_enums_count;
extern const UtilitySpec utility_functions[];
extern const int utility_functions_count;
extern const char *builtin_class_names[];
extern const int builtin_class_names_count;

} // namespace gdas::gen

#endif // BUILTIN_BINDINGS_GEN_H
