#!/usr/bin/env python3
"""Generates C++ data tables from godot-cpp's extension_api.json.

The tables drive the registration of Godot builtin classes (Vector2, Array,
String methods, ...), global enums, and utility functions with the
AngelScript engine at runtime. Registration/dispatch code lives in
extension/src/binding/builtin_types.cpp; this file only emits data.

Usage: gen_bindings.py <extension_api.json> <output.gen.cpp>
"""

import json
import sys

# Builtin classes that are registered as AngelScript value types. String is
# handled separately (string factory) but still gets its methods from here.
SKIP_CLASSES = {"Nil", "bool", "int", "float"}

# AngelScript reserved words that cannot be used as identifiers.
AS_RESERVED = {
    "and", "abstract", "auto", "bool", "break", "case", "cast", "catch",
    "class", "const", "continue", "default", "do", "double", "else", "enum",
    "explicit", "external", "false", "final", "float", "for", "foreach",
    "from", "funcdef", "function", "get", "if", "import", "in", "inout",
    "int", "interface", "int8", "int16", "int32", "int64", "is", "mixin",
    "namespace", "not", "null", "or", "out", "override", "private",
    "property", "protected", "return", "set", "shared", "super", "switch",
    "this", "true", "try", "typedef", "uint", "uint8", "uint16", "uint32",
    "uint64", "void", "while", "xor",
}


def c_str(s):
    if s is None:
        return "nullptr"
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def safe_ident(name):
    return name + "_" if name in AS_RESERVED else name


def main():
    api_path, out_path = sys.argv[1], sys.argv[2]
    with open(api_path) as f:
        api = json.load(f)

    operators = []

    lines = [
        "// Generated by tools/gen_bindings.py from extension_api.json. Do not edit.",
        '#include "builtin_bindings.gen.h"',
        "",
        "namespace gdas::gen {",
        "",
    ]

    arg_blocks = []
    arg_block_index = {}

    def emit_args(args):
        """Deduplicate identical argument lists into shared arrays."""
        key = tuple((a["name"], a["type"], a.get("default_value")) for a in args)
        if not key:
            return "nullptr"
        if key in arg_block_index:
            return arg_block_index[key]
        name = f"args_{len(arg_blocks)}"
        rows = ", ".join(
            "{ %s, %s, %s }" % (c_str(safe_ident(a["name"])), c_str(a["type"]), c_str(a.get("default_value")))
            for a in args
        )
        arg_blocks.append(f"static const ArgSpec {name}[] = {{ {rows} }};")
        arg_block_index[key] = name
        return name

    methods = []
    ctors = []
    members = []
    class_names = []

    for cls in api["builtin_classes"]:
        cname = cls["name"]
        if cname in SKIP_CLASSES:
            # Keep operators like `float * Vector2` by attaching them to the
            # class on the right-hand side as reversed operators.
            if cname in ("int", "float", "bool"):
                for op in cls.get("operators", []):
                    right = op.get("right_type")
                    if right and right not in SKIP_CLASSES and right != "Variant":
                        operators.append(
                            "{ %s, %s, %s, %s, true }" % (
                                c_str(right), c_str(op["name"]),
                                c_str(cname), c_str(op["return_type"]),
                            )
                        )
            continue
        class_names.append(cname)
        for m in cls.get("methods", []):
            args = m.get("arguments", [])
            methods.append(
                "{ %s, %s, %s, %s, %s, %s, %d, %s }" % (
                    c_str(cname), c_str(safe_ident(m["name"])), c_str(m["name"]),
                    c_str(m.get("return_type")),
                    "true" if m["is_vararg"] else "false",
                    "true" if m["is_static"] else "false",
                    len(args), emit_args(args),
                )
            )
        for op in cls.get("operators", []):
            operators.append(
                "{ %s, %s, %s, %s, false }" % (
                    c_str(cname), c_str(op["name"]),
                    c_str(op.get("right_type")), c_str(op["return_type"]),
                )
            )
        for ct in cls.get("constructors", []):
            args = ct.get("arguments", [])
            ctors.append(
                "{ %s, %d, %d, %s }" % (c_str(cname), ct["index"], len(args), emit_args(args))
            )
        for mem in cls.get("members", []):
            members.append(
                "{ %s, %s, %s }" % (c_str(cname), c_str(mem["name"]), c_str(mem["type"]))
            )

    enum_values = []
    enums = []
    for en in api["global_enums"]:
        if en["name"].startswith("Variant."):
            continue
        start = len(enum_values)
        for v in en["values"]:
            enum_values.append("{ %s, %dLL }" % (c_str(v["name"]), v["value"]))
        enums.append(
            "{ %s, %s, %d, %d }" % (
                c_str(en["name"]), "true" if en["is_bitfield"] else "false",
                start, len(en["values"]),
            )
        )

    utilities = []
    for u in api["utility_functions"]:
        args = u.get("arguments", [])
        utilities.append(
            "{ %s, %s, %s, %d, %d, %s }" % (
                c_str(safe_ident(u["name"])), c_str(u.get("return_type")),
                "true" if u["is_vararg"] else "false",
                u["hash"], len(args), emit_args(args),
            )
        )

    lines.extend(arg_blocks)
    lines.append("")

    def emit_table(type_name, var_name, rows):
        lines.append(f"const {type_name} {var_name}[] = {{")
        for r in rows:
            lines.append(f"\t{r},")
        lines.append("};")
        lines.append(f"const int {var_name}_count = {len(rows)};")
        lines.append("")

    emit_table("MethodSpec", "builtin_methods", methods)
    emit_table("OperatorSpec", "builtin_operators", operators)
    emit_table("CtorSpec", "builtin_ctors", ctors)
    emit_table("MemberSpec", "builtin_members", members)
    emit_table("EnumValSpec", "global_enum_values", enum_values)
    emit_table("EnumSpec", "global_enums", enums)
    emit_table("UtilitySpec", "utility_functions", utilities)

    names = ", ".join(c_str(n) for n in class_names)
    lines.append(f"const char *builtin_class_names[] = {{ {names} }};")
    lines.append(f"const int builtin_class_names_count = {len(class_names)};")
    lines.append("")
    lines.append("} // namespace gdas::gen")
    lines.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    main()
